### ISSUE TITLE
Bad control character error message in Facebook time/location tabs

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#1042]
This happened to me within the Facebook experience

<img width="1244" alt="Screenshot 2022-10-05 at 16 21 51" src="https://user-images.githubusercontent.com/1473244/194098610-78586967-c0ec-4de9-80fa-c2cd5aee5a4e.png">

Console contains

```
TheDataExperience.onUnitFilesUpdate.initFileManager: 124922.28686523438 ms
889e02d.js:8 TheDataExperience.onUnitFilesUpdate.DBMS.createDB: 16.141845703125 ms
889e02d.js:8 TheDataExperience.onUnitFilesUpdate.DBMS.generateRecords: 4161.412841796875 ms
889e02d.js:8 TheDataExperience.onUnitFilesUpdate.DBMS.insertRecords: 563.81494140625 ms
889e02d.js:8 TheDataExperience.onUnitFilesUpdate.DBMS: 4741.665771484375 ms
889e02d.js:8 TheDataExperience.onUnitFilesUpdate: 129666.68408203125 ms
2889e02d.js:8 SyntaxError: Bad control character in string literal in JSON at position 171168
    at JSON.parse (<anonymous>)
    at t (dc0e2fa.js:1:13786)
    at e.<anonymous> (889e02d.js:8:38202)
    at v (213223f.js:2:78901)
    at Generator._invoke (213223f.js:2:78689)
    at Generator.next (213223f.js:2:79330)
    at e (96c27e5.js:2:39328)
    at m (96c27e5.js:2:39531)
onUnitResultsUpdate @ 889e02d.js:8
```

I'm afraid i can't share the facebook download file as it is my own personal data and too sensitive to share.

**Comment by alexbfree** [comment]
This is currently blocking last couple of tests on #932

**Comment by alexbfree** [comment]
@fquellec suggests a fix would be that scanning continues skipping over any file with an error in parsing.
